networks:
  app-network:

services:

  compreface-relay:
    restart: always
    container_name: compreface-relay
    image: compreface-relay:latest
    networks:
      - app-network
    ports:
      - 8005:8005
