spring:

# Not accessing the real Postgres database at this stage but keep for possible future use
#  datasource:
#    url: jdbc:postgresql://compreface-postgres-db/frs
#    username: postgres
#    password: postgres
#  jpa:
#    properties:
#      hibernate:
#        default_schema: public
#        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQL10Dialect
#    hibernate:
#      ddl-auto: none
  datasource:
    # url: jdbc:h2:mem:comprefacedb
    url: jdbc:h2:mem:RelayDatabase;MODE=PostgreSQL;
    username: sa
    password: password
  jpa:
    properties:
      hibernate:
        default_schema: public
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

server:
  port: 8005

# Logging options
logging:
  dump-headers: false
  level:
    org.springframework: INFO
    aero.sita: INFO

# App properties
app.name: CompreFace Relay
app.version: 1.0

# Gallery Service websocket URL, message size in MB and WS heart beat and connection retry intervals
app.feeder.ws.url: wss://gallery-services-staging.sitalab.io/gallery
app.feeder.ws.message.size: 3
app.feeder.ws.connect.interval: 30
app.feeder.ws.heartbeat.interval: 45

# CompreFace API endpoint
app.feeder.compreface.url: http://192.168.1.181:8080
app.feeder.recognition.application: Digital Travel Lane
# if the recognition application apikey cannot be retrieved then use this apikey
app.feeder.recognition.apikey: 2688d27d-de70-46b4-82e7-1468bb0abab7
app.feeder.compreface.detection.threshold: 0.8

# Itinerary defaults
app.feeder.terminal: 1
app.feeder.location: Loyang
app.feeder.country: SG
app.feeder.port: TGA
app.feeder.alt.country: AU
app.feeder.alt.port: SYD
app.feeder.flight: QF1234

# Logging mask filter for privacy
app.mask.logging: false

# Swagger
swagger.enabled: true

---

spring:
  config.activate.on-profile: local

server:
  port: 8006

# Logging options
logging:
  level:
    org.springframework: INFO
    aero.sita: DEBUG

# CompreFace endpoint
app.feeder.compreface.url: http://localhost:8081

# Gallery Service websocket URL, message size in MB and WS heart beat and connection retry intervals
app.feeder.ws.url: ws://localhost:8002/gallery
app.feeder.ws.message.size: 1
app.feeder.ws.connect.interval: 30
app.feeder.ws.heartbeat.interval: 45
app.feeder.ws.disable.ssl: true

---

spring:
  config.activate.on-profile: damien

# CompreFace API endpoint
app.feeder.compreface.url: http://10.0.0.127:8080
app.feeder.recognition.apikey: 2688d27d-de70-46b4-82e7-1468bb0abab7
